import { NextRequest, NextResponse } from 'next/server';
import { getValidAccessToken } from '@/lib/spotify/auth';
import { spotifyFetch, createPlaylist, addTracksToPlaylist } from '@/lib/spotify/client';

interface CreatePlaylistBody {
  sessionTitle: string;
  sessionSubtitle?: string;
  uris: string[];
}

export async function POST(req: NextRequest) {
  const token = await getValidAccessToken();
  if (!token) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  }

  const body = (await req.json()) as CreatePlaylistBody;
  const { sessionTitle, sessionSubtitle, uris } = body;

  if (!sessionTitle?.trim()) {
    return NextResponse.json({ error: 'sessionTitle is required' }, { status: 400 });
  }

  if (!uris || uris.length === 0) {
    return NextResponse.json({ error: 'No track URIs provided' }, { status: 400 });
  }

  // Filter to valid track URIs only — episodes and empty strings are excluded.
  // The client pre-filters before sending, so this is a safety net.
  const trackUris = uris.filter((u) => u.startsWith('spotify:track:'));

  if (trackUris.length === 0) {
    return NextResponse.json(
      { error: 'No valid Spotify track URIs found. Regenerate this session with Spotify connected to get real track links.' },
      { status: 400 }
    );
  }

  // Get user ID — needed for playlist creation endpoint
  let profile: { id: string };
  let playlist: { id: string; external_urls: { spotify: string } };
  try {
    profile = await spotifyFetch<{ id: string }>('/me', token);

    // Create playlist with branded name: "Moodcast — {sessionTitle}"
    const playlistName = `Moodcast — ${sessionTitle}`;
    playlist = await createPlaylist(
      token,
      profile.id,
      playlistName,
      sessionSubtitle ? `Moodcast: ${sessionSubtitle}` : 'Generated by Moodcast'
    );

    // Add tracks (batched automatically inside addTracksToPlaylist)
    await addTracksToPlaylist(token, playlist.id, trackUris);
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Spotify API error';
    return NextResponse.json({ error: msg }, { status: 502 });
  }

  return NextResponse.json({
    playlistId: playlist.id,
    playlistUrl: playlist.external_urls.spotify,
  });
}
