import { NextRequest, NextResponse } from 'next/server';
import { getValidAccessToken } from '@/lib/spotify/auth';
import { createPlaylist, SpotifyAPIError } from '@/lib/spotify/client';

interface CreatePlaylistBody {
  sessionTitle: string;
  sessionSubtitle?: string;
  uris: string[];
}

type AddResult = { ok: boolean; status: number; body: unknown };

async function addViaJsonBody(token: string, playlistId: string, uris: string[]): Promise<AddResult> {
  const res = await fetch(`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ uris }),
  });
  let body: unknown;
  try { body = await res.json(); } catch { body = null; }
  return { ok: res.ok, status: res.status, body };
}

async function addViaQueryParam(token: string, playlistId: string, uris: string[]): Promise<AddResult> {
  // Spotify also accepts uris as a comma-separated query param (max ~2000 chars URL)
  const uriParam = uris.map(encodeURIComponent).join(',');
  const res = await fetch(
    `https://api.spotify.com/v1/playlists/${playlistId}/tracks?uris=${uriParam}`,
    {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}` },
    }
  );
  let body: unknown;
  try { body = await res.json(); } catch { body = null; }
  return { ok: res.ok, status: res.status, body };
}

export async function POST(req: NextRequest) {
  const token = await getValidAccessToken();
  if (!token) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  }

  const body = (await req.json()) as CreatePlaylistBody;
  const { sessionTitle, sessionSubtitle, uris } = body;

  if (!sessionTitle?.trim()) {
    return NextResponse.json({ error: 'sessionTitle is required' }, { status: 400 });
  }

  if (!uris || uris.length === 0) {
    return NextResponse.json({ error: 'No track URIs provided' }, { status: 400 });
  }

  const trackUris = uris.filter((u) => u.startsWith('spotify:track:'));

  if (trackUris.length === 0) {
    return NextResponse.json(
      { error: 'No valid Spotify track URIs found. Regenerate this session with Spotify connected to get real track links.' },
      { status: 400 }
    );
  }

  // Create the playlist
  const playlistName = `Moodcast — ${sessionTitle}`;
  const description = sessionSubtitle ? `Moodcast: ${sessionSubtitle}` : 'Generated by Moodcast';

  let playlist: { id: string; external_urls: { spotify: string } };
  try {
    playlist = await createPlaylist(token, playlistName, description);
    console.log('[playlist/create] created:', playlist.id);
  } catch (err) {
    if (err instanceof SpotifyAPIError) {
      console.error('[playlist/create] createPlaylist failed:', err.status, err.spotifyMessage);
      if (process.env.NODE_ENV !== 'production') {
        return NextResponse.json(
          { ok: false, failedStep: 'createPlaylist', spotifyStatus: err.status, spotifyError: { message: err.spotifyMessage, reason: err.spotifyReason } },
          { status: err.status }
        );
      }
    }
    const msg = err instanceof Error ? err.message : 'Playlist creation failed';
    return NextResponse.json({ error: msg }, { status: 502 });
  }

  // Add tracks — try JSON body first, then query-param fallback
  console.log('[playlist/create] adding', trackUris.length, 'tracks to', playlist.id);

  let method = 'json';

  for (let i = 0; i < trackUris.length; i += 100) {
    const batch = trackUris.slice(i, i + 100);

    const jsonResult = await addViaJsonBody(token, playlist.id, batch);
    console.log('[playlist/create] addTracks batch', i / 100, 'json:', jsonResult.status);

    if (jsonResult.ok) continue;

    // JSON body failed — try query param
    const queryResult = await addViaQueryParam(token, playlist.id, batch);
    console.log('[playlist/create] addTracks batch', i / 100, 'queryparam:', queryResult.status);

    if (queryResult.ok) {
      method = 'queryparam';
      continue;
    }

    // Both methods failed
    console.error('[playlist/create] addTracks failed (both methods):', {
      jsonStatus: jsonResult.status, jsonBody: jsonResult.body,
      queryStatus: queryResult.status, queryBody: queryResult.body,
    });

    // Keep the empty playlist — return its URL so user can delete or add tracks manually
    return NextResponse.json(
      {
        ok: false,
        error: 'Playlist was created, but Spotify rejected adding tracks. You can open the playlist and add tracks manually, or delete it.',
        playlistId: playlist.id,
        playlistUrl: playlist.external_urls.spotify,
        ...(process.env.NODE_ENV !== 'production' && {
          debug: {
            failedStep: 'addTracksToPlaylist',
            jsonResult,
            queryResult,
          },
        }),
      },
      { status: 207 }
    );
  }

  console.log('[playlist/create] all tracks added via', method);

  return NextResponse.json({
    playlistId: playlist.id,
    playlistUrl: playlist.external_urls.spotify,
  });
}
