// lib/demo/demoSessions.ts
import type { SavedSession } from '@/lib/types/moodcast';

export const DEMO_SESSIONS: SavedSession[] = [
  {
    id: 'demo-debugging',
    createdAt: '2026-05-04T02:14:00Z',
    isDemo: true,
    sessionTitle: 'Late Night Debugging FM',
    sessionSubtitle: 'A 45-minute focus session for the tired but emotionally awake.',
    mood: 'tired, melancholic',
    activity: 'coding',
    energyArc: 'medium → low',
    openingMonologue:
      "It's late. The screen is still too bright, and you've got one more thing to finish — the kind of thing that keeps you up not because it has to, but because you need it to feel right before you can sleep.\n\nWe're starting soft. Not because you're done — but because you need a way back into the work. Something that keeps the room quiet without making it feel empty.\n\nThis is your 45 minutes. Let's go.",
    tracks: [
      {
        title: 'Holocene',
        artist: 'Bon Iver',
        moodTag: 'melancholic',
        energy: 'low',
        whyItFits: "Opens the space without demanding attention. The guitar sits in the background like a thought you haven't finished yet.",
        transitionLine: 'The next one keeps the stillness going, but pulls you a little deeper in.',
      },
      {
        title: 'Night Owl',
        artist: 'Khruangbin',
        moodTag: 'drifting',
        energy: 'low',
        whyItFits: 'Instrumental groove that feels like a room full of ideas but no pressure to have them yet.',
        transitionLine: 'Time to let the keyboard take over.',
      },
      {
        title: 'Motion Picture Soundtrack',
        artist: 'Radiohead',
        moodTag: 'melancholic',
        energy: 'low',
        whyItFits: 'For the moment when you realize the problem is harder than you thought. Somehow that is comforting.',
        transitionLine: 'Coming up — something to anchor you back.',
      },
      {
        title: 'Pink + White',
        artist: 'Frank Ocean',
        moodTag: 'nostalgic',
        energy: 'medium',
        whyItFits: 'A little warmth in the middle of the session. A reminder that this moment will become a memory.',
        transitionLine: 'Now deep into the focus zone.',
      },
      {
        title: '4 AM',
        artist: 'Rival Consoles',
        moodTag: 'focused',
        energy: 'medium',
        whyItFits: 'Pure signal. Electronic minimalism that clears the mental noise and lets you lock in.',
        transitionLine: 'One more thing before we wind down.',
      },
      {
        title: 'Retrograde',
        artist: 'James Blake',
        moodTag: 'emotional',
        energy: 'medium',
        whyItFits: 'The emotional peak of the session — a track that acknowledges how much you are carrying.',
        transitionLine: 'Starting to cool. Let the work settle.',
      },
      {
        title: 'Re: Stacks',
        artist: 'Bon Iver',
        moodTag: 'reflective',
        energy: 'low',
        whyItFits: 'A closing breath. Sparse, patient, honest. Good for the last few minutes of work.',
        transitionLine: 'And to close the room quietly—',
      },
      {
        title: 'Limit to Your Love',
        artist: 'James Blake',
        moodTag: 'quiet',
        energy: 'low',
        whyItFits: "Slow and low. The kind of song that makes it okay to stop. You've done enough.",
        transitionLine: '',
      },
    ],
    sessionArc: [
      { phase: 'Opening Atmosphere', description: 'Soft entry — ease into the room, not the work' },
      { phase: 'Focus Zone', description: 'Steady, ambient — deep work window opens' },
      { phase: 'Emotional Peak', description: 'Something with feeling — reward the effort' },
      { phase: 'Landing', description: 'Cool down, let go, close the loop' },
    ],
    endingMessage:
      "That's the session. You made it through — or at least you're closer than when you started. The room can go quiet now. You did enough.",
  },
  {
    id: 'demo-study',
    createdAt: '2026-05-03T14:30:00Z',
    isDemo: true,
    sessionTitle: 'Rainy Study Room',
    sessionSubtitle: 'A 30-minute session for calm concentration and clear thinking.',
    mood: 'calm, reflective',
    activity: 'studying',
    energyArc: 'low → medium',
    openingMonologue:
      "The kind of afternoon that makes you want to think carefully. Outside, the rain handles all the noise — you get the quiet.\n\nWe are starting slow and building slowly. No rush. The material will come.",
    tracks: [
      {
        title: 'Experience',
        artist: 'Ludovico Einaudi',
        moodTag: 'calm',
        energy: 'low',
        whyItFits: 'Piano minimalism that creates space around every thought. Nothing competes with your reading.',
        transitionLine: 'Staying in the quiet, but adding a little texture.',
      },
      {
        title: 'Spiegel im Spiegel',
        artist: 'Arvo Pärt',
        moodTag: 'reflective',
        energy: 'low',
        whyItFits: 'Mirror and repetition — the sonic equivalent of re-reading a paragraph until it clicks.',
        transitionLine: 'Time to bring the focus up slightly.',
      },
      {
        title: 'Gymnopédie No.1',
        artist: 'Erik Satie',
        moodTag: 'gentle',
        energy: 'low',
        whyItFits: 'One of the oldest study companions. Still works. There is nothing wrong with what works.',
        transitionLine: 'Shifting into something a little more present.',
      },
      {
        title: "Comptine d'un autre été",
        artist: 'Yann Tiersen',
        moodTag: 'focused',
        energy: 'medium',
        whyItFits: 'The familiar melody of focus. Slightly more animated — good for the second half of a study block.',
        transitionLine: 'Closing the session with intention.',
      },
      {
        title: 'On the Nature of Daylight',
        artist: 'Max Richter',
        moodTag: 'reflective',
        energy: 'low',
        whyItFits: 'A soft landing. Let what you learned settle before you close the books.',
        transitionLine: '',
      },
    ],
    sessionArc: [
      { phase: 'Opening', description: 'Settle in, clear the mental workspace' },
      { phase: 'Concentration', description: 'Quiet, consistent energy for reading and note-taking' },
      { phase: 'Integration', description: 'Material starting to connect — let the music reflect that' },
      { phase: 'Rest', description: 'Close the session gently' },
    ],
    endingMessage: 'Session complete. Whatever you learned today is already yours.',
  },
  {
    id: 'demo-sunday',
    createdAt: '2026-05-04T10:00:00Z',
    isDemo: true,
    sessionTitle: 'Sunday Reset',
    sessionSubtitle: 'A 30-minute companion for soft mornings and slow starts.',
    mood: 'soft, hopeful',
    activity: 'cleaning / planning',
    energyArc: 'gradually rising',
    openingMonologue:
      "Sunday. The week is over and hasn't started yet. This is the small window when everything feels possible.\n\nWe are going to move slowly at first. Let the room wake up with you.",
    tracks: [
      {
        title: 'Golden Hour',
        artist: 'JVKE',
        moodTag: 'hopeful',
        energy: 'low',
        whyItFits: 'Warm and gentle. Good for the first ten minutes before the coffee is ready.',
        transitionLine: 'A little more movement now.',
      },
      {
        title: 'Coffee',
        artist: 'beabadoobee',
        moodTag: 'soft',
        energy: 'medium',
        whyItFits: 'Indie warmth. Familiar enough to feel like home, just enough energy to start moving.',
        transitionLine: 'Getting into rhythm.',
      },
      {
        title: 'Bloom',
        artist: 'The Paper Kites',
        moodTag: 'gentle',
        energy: 'medium',
        whyItFits: 'Acoustic and clean. Good for making lists and thinking through the week ahead.',
        transitionLine: 'Keeping the momentum.',
      },
      {
        title: 'Sunday Morning',
        artist: 'Maroon 5',
        moodTag: 'warm',
        energy: 'medium',
        whyItFits: 'A classic for a reason. Familiar, easy, genuinely good.',
        transitionLine: 'Closing gently.',
      },
      {
        title: 'The Night Will Always Win',
        artist: 'Manchester Orchestra',
        moodTag: 'reflective',
        energy: 'low',
        whyItFits: 'A quiet close. The week will come, but right now there is still this.',
        transitionLine: '',
      },
    ],
    sessionArc: [
      { phase: 'Waking', description: 'Soft, no demands — just presence' },
      { phase: 'Moving', description: 'Light energy for tidying, coffee, small tasks' },
      { phase: 'Planning', description: 'Clear-headed — good for writing, thinking, to-do lists' },
      { phase: 'Closing', description: 'Settle before the week arrives' },
    ],
    endingMessage: 'The week will be what it will be. You gave yourself a good start.',
  },
  {
    id: 'demo-design',
    createdAt: '2026-05-02T11:00:00Z',
    isDemo: true,
    sessionTitle: 'Design Sprint Radio',
    sessionSubtitle: 'A 45-minute energized session for creative momentum.',
    mood: 'energetic, creative',
    activity: 'designing',
    energyArc: 'high → medium',
    openingMonologue:
      "You have ideas. The problem right now is getting them out of your head and into something real.\n\nThis session is going to push. We start hot and let it settle into focus. Stay with it.",
    tracks: [
      {
        title: 'Electric Feel',
        artist: 'MGMT',
        moodTag: 'energetic',
        energy: 'high',
        whyItFits: 'Opens at full voltage. The kind of song that makes you reach for the pen.',
        transitionLine: 'Keep the energy, shift the direction.',
      },
      {
        title: 'Instant Crush',
        artist: 'Daft Punk ft. Julian Casablancas',
        moodTag: 'creative',
        energy: 'high',
        whyItFits: 'Groove and cool in equal parts. Good for laying out ideas without second-guessing.',
        transitionLine: 'Stepping into flow state.',
      },
      {
        title: 'Get Lucky',
        artist: 'Daft Punk ft. Pharrell Williams',
        moodTag: 'upbeat',
        energy: 'high',
        whyItFits: 'Pure momentum. If you are stuck, this unsticks you.',
        transitionLine: 'Shifting into deep work mode now.',
      },
      {
        title: 'Midnight City',
        artist: 'M83',
        moodTag: 'expansive',
        energy: 'medium',
        whyItFits: 'The midpoint shift. From excitement to vision. Let the ideas breathe.',
        transitionLine: 'Still in flow, slightly cooler.',
      },
      {
        title: 'Oblivion',
        artist: 'Grimes',
        moodTag: 'dreamy',
        energy: 'medium',
        whyItFits: 'Hypnotic and focused. Good for refinement work — when the concept is there and you are making it right.',
        transitionLine: 'One final push.',
      },
      {
        title: 'Crystalised',
        artist: 'The xx',
        moodTag: 'minimal',
        energy: 'medium',
        whyItFits: 'Cool and clean. The design equivalent of whitespace.',
        transitionLine: '',
      },
    ],
    sessionArc: [
      { phase: 'Ignition', description: 'High energy — generate without filtering' },
      { phase: 'Sprint', description: 'Fast decisions, strong momentum' },
      { phase: 'Flow', description: 'Ideas connecting — deep creative work' },
      { phase: 'Refine', description: 'Polish and clarify' },
    ],
    endingMessage: 'Sprint done. Whatever is on the canvas is real now. Ship it or sleep on it.',
  },
  {
    id: 'demo-walk',
    createdAt: '2026-05-03T23:00:00Z',
    isDemo: true,
    sessionTitle: 'Midnight Walk',
    sessionSubtitle: 'A 20-minute session for late streets and thinking through things.',
    mood: 'nostalgic, lonely but peaceful',
    activity: 'walking',
    energyArc: 'low',
    openingMonologue:
      "Late. The city is down to its essential sounds. You are not going anywhere in particular — you are just moving.\n\nThis session does not demand anything from you. It is just company.",
    tracks: [
      {
        title: 'The Night',
        artist: 'Zac Brown Band',
        moodTag: 'nostalgic',
        energy: 'low',
        whyItFits: 'A late-night companion. Honest and unhurried.',
        transitionLine: 'Staying in the feeling.',
      },
      {
        title: 'Street Lights',
        artist: 'Kanye West',
        moodTag: 'reflective',
        energy: 'low',
        whyItFits: 'Two minutes of everything you have been trying to articulate tonight.',
        transitionLine: 'A little quieter now.',
      },
      {
        title: 'Skinny Love',
        artist: 'Bon Iver',
        moodTag: 'lonely',
        energy: 'low',
        whyItFits: 'For the things you are still figuring out. There is no rush.',
        transitionLine: 'Closing out the walk.',
      },
      {
        title: 'Lua',
        artist: 'Bright Eyes',
        moodTag: 'tender',
        energy: 'low',
        whyItFits: 'Honest and gentle. The right song for the last few blocks home.',
        transitionLine: '',
      },
    ],
    sessionArc: [
      { phase: 'Walking', description: 'Moving without destination' },
      { phase: 'Thinking', description: 'The kind of thinking that only happens when you are moving' },
      { phase: 'Arriving', description: 'Coming back — to yourself, to home, to wherever' },
    ],
    endingMessage: "You figured out something tonight. Maybe you know what it is. Either way — good walk.",
  },
];

export function getDemoSession(id: string): SavedSession | null {
  return DEMO_SESSIONS.find((s) => s.id === id) ?? null;
}

export function getRandomDemoSession(): SavedSession {
  return DEMO_SESSIONS[Math.floor(Math.random() * DEMO_SESSIONS.length)];
}
