#!/usr/bin/env tsx
//
// Generates a double-clickable `Moodcast.command` for macOS Finder. The
// .command file is a tiny shell script that:
//   1. cds into this repo
//   2. runs `moodcast up` to boot the dev server (or open the browser if it
//      is already running)
//
// Usage:
//   npx tsx scripts/create-mac-launcher.ts            → writes ~/Desktop/Moodcast.command
//   npx tsx scripts/create-mac-launcher.ts ~/Apps     → writes there instead
//
// The output file is gitignored — generated launchers are user-specific.
// Re-running overwrites the existing file (idempotent).

import fs from 'fs';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

function repoRoot(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, '..');
}

function targetDir(): string {
  const arg = process.argv[2];
  if (!arg) return path.join(os.homedir(), 'Desktop');
  return path.resolve(arg.startsWith('~') ? arg.replace('~', os.homedir()) : arg);
}

function buildScript(root: string): string {
  // `command -v moodcast` checks if the user installed the alias from
  // `moodcast setup`. If yes, prefer it (already on PATH, lighter spawn).
  // Otherwise fall back to the in-repo `npm run moodcast:up`.
  return [
    '#!/bin/zsh',
    '# Moodcast launcher — auto-generated by scripts/create-mac-launcher.ts.',
    '# Edit only if you know what you are doing; re-run the script to regenerate.',
    'set -e',
    `MOODCAST_REPO="${root}"`,
    'cd "$MOODCAST_REPO"',
    '',
    '# Source the user shell profile so the `moodcast` alias (if installed by',
    '# `moodcast setup`) is available even when launched from Finder.',
    '[[ -f "$HOME/.zshrc" ]] && source "$HOME/.zshrc"',
    '',
    'if command -v moodcast >/dev/null 2>&1; then',
    '  moodcast up',
    'else',
    '  npm --prefix "$MOODCAST_REPO" run --silent moodcast:up',
    'fi',
    '',
    'echo ""',
    'echo "Moodcast is up. You can close this window."',
    '',
  ].join('\n');
}

function main(): void {
  const root = repoRoot();
  const dir = targetDir();
  if (!fs.existsSync(dir)) {
    console.error(`✗ target directory does not exist: ${dir}`);
    process.exit(1);
  }
  const file = path.join(dir, 'Moodcast.command');
  fs.writeFileSync(file, buildScript(root), { mode: 0o755 });
  console.log(`✓ wrote launcher: ${file}`);
  console.log('  Double-click it from Finder to start Moodcast.');
  console.log('  First run: macOS may ask "Cannot verify developer" — open');
  console.log('  System Settings → Privacy & Security → Open Anyway, just once.');
}

main();
